import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


const faviconVersion = "v1.2"; // Declare it here

export const metadata: Metadata = {
  title: {
    template: "%s | Welcome to Alpha Fix",
    default: "Alpha Fix | Rosenberg – Fast & Reliable Mobile Repair Experts",
  },
  description: "Looking for quick and trusted phone repairs? At Alpha Fix, we fix cracked screens, battery issues, and more—all at unbeatable prices. Walk in today and experience professional service with a personal touch.",
  icons: {
    icon: [
      // `/assets/logo/Author-Logo.png?v=${faviconVersion}`,
      // "/favicon.ico",
      { url: "/assets/logo/Alpha-fix.jpg" },
    ],
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
